language: ruby
before_install: gem install rjack-tarpit -v=2.0.3
bundler_args: ""
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-1.6.8
  - jruby-1.6.8 --1.9
  - jruby-18mode
  - jruby-19mode
  - jruby-head-d_2013_09_22
script: "bundle exec rake test"
